### ISSUE TITLE
关于 nr database 的问题

### ISSUE THREAD

**Issue by zw-SIMM** [LiamT01/CTR#1]
您好，您的模型看上去性能非常优秀！我想请教一下，
如果我想使用自己的数据集，具体应该如何生成pssm矩阵呢？ 
是否需要从https://ftp.ncbi.nlm.nih.gov/blast/db/ 下载所有包含`nr`的数据集，然后再运行 `.get_pssm.sh` ? 
但我看数据集有好几十个G，有没有更方便的方法预测某一个蛋白序列的突变？

**Comment by LiamT01** [comment]
您好，感谢您了解这个研究。

您需要下载用于BLAST的数据库。我们在研究时使用的是non-redundant (nr)，我们也推荐您使用nr数据库，因为它包含的蛋白质种类更多，几乎能满足任何研究需求。完整的nr数据库在解压后的体积有数百GB。如果您不方便下载或者存储，也可以选择其他更轻量的数据库，但您自己数据集里的某些蛋白质可能不在其中。

您可以在<https://www.uppmax.uu.se/resurser/databases/blast-databases/>的表格中查看可用的蛋白质数据库，并选择符合您研究需求的、体积更小的数据库。然后请参考<https://www.ncbi.nlm.nih.gov/books/NBK569850/>并按照其中的提示使用脚本下载数据库。我们不推荐从<https://ftp.ncbi.nlm.nih.gov/blast/db/>手动下载数据库。

在安装好BLAST软件以及准备好相关数据库后，请将您数据集中的蛋白质序列保存在`./data/seq`文件夹中，并以蛋白质的chain命名这些文件。请您按照`./get_pssm.sh`中的注释修改`BLASTDB`变量和`/path/to/blast/bin/psiblast`路径，然后即可运行该脚本使用psiblast工具计算PSSM矩阵。

Hongwei Tu

**Comment by zhangwei1717** [comment]
非常感谢您快速且详细的回复！感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hongwei ***@***.***&gt;; 
发送时间: 2022年12月5日(星期一) 中午1:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LiamT01/CTR] 关于 nr database 的问题 (Issue #1)





 
您好，感谢您了解这个研究。
 
您需要下载用于BLAST的数据库。我们在研究时使用的是non-redundant (nr)，我们也推荐您使用nr数据库，因为它包含的蛋白质种类更多，几乎能满足任何研究需求。完整的nr数据库在解压后的体积有数百GB。如果您不方便下载或者存储，也可以选择其他更轻量的数据库，但您自己数据集里的某些蛋白质可能不在其中。
 
您可以在https://www.uppmax.uu.se/resurser/databases/blast-databases/的表格中查看可用的蛋白质数据库，并选择符合您研究需求的、体积更小的数据库。然后请参考https://www.ncbi.nlm.nih.gov/books/NBK569850/并按照其中的提示使用脚本下载数据库。我们不推荐从https://ftp.ncbi.nlm.nih.gov/blast/db/手动下载数据库。
 
在安装好BLAST软件以及准备好相关数据库后，请将您数据集中的蛋白质序列保存在./data/seq文件夹中，并以蛋白质的chain命名这些文件。请您按照./get_pssm.sh中的注释修改BLASTDB变量和/path/to/blast/bin/psiblast路径，然后即可运行该脚本使用psiblast工具计算PSSM矩阵。
 
Hongwei Tu

**Comment by zhangwei1717** [comment]
您好，我能再请教一下生成一个ppsm矩阵大概要多久吗？
我基于nr数据集生成1ACB蛋白序列的ppsm好像就要半小时以上？
而且还没有运行完成的迹象，下载生成的ppsm文件来看只有前43行
![image](https://user-images.githubusercontent.com/72490988/205638063-060277f3-43f4-46e9-a6e4-c55a080f294d.png)

**Comment by LiamT01** [comment]
您好。

生成一个PSSM矩阵的耗时取决于蛋白质种类和电脑配置。我们进行实验时，大多数蛋白质序列耗时20-50分钟左右。1ACB的序列不算特别长，我印象里耗时30分钟左右。

您的耗时稍长，但PSSM矩阵的计算量确实很大。如果耗时是小时级别，应该都在正常范围内。您可以继续尝试其他蛋白质序列，测试一下耗时是否会逐渐稳定。

**Comment by zhangwei1717** [comment]
谢谢，刚才已经生成PSSM矩阵了，用时约几十分钟。
谢谢您又这么快的回复！
另外，我还想请教一个问题，模型在训练时保存了很多模型，在推理时是否需要将所有模型推理一遍取均值？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LiamT01/CTR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月5日(星期一) 晚上10:04
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [LiamT01/CTR] 关于 nr database 的问题 (Issue #1)





 
您好。
 
生成一个PSSM矩阵的耗时取决于蛋白质种类和电脑配置。我们进行实验时，大多数蛋白质序列耗时20-50分钟左右。1ACB的序列不算特别长，我印象里耗时30分钟左右。
 
您的耗时稍长，但PSSM矩阵的计算量确实很大。如果耗时是小时级别，应该都在正常范围内。您可以继续尝试其他蛋白质序列，测试一下耗时是否会逐渐稳定。

**Comment by LiamT01** [comment]
哈哈，不用客气，有任何问题欢迎随时交流。

目前最新版本的代码没有采取“取均值”的方法，而是让用户自己选择交叉验证中某一折保存下来的模型用于推理。我认为，一般的场景下任意选取某一个模型就可以了。当然，如果您想取均值也是可以的，有一点类似于集成学习中使用多个学习器的方法。
